#!/bin/bash
echoerr() { echo "$@" 1>&2; }
do_ip6tables() {
    if [ "$DEBUG" == "1" ]; then
        echo "ip6tables $@"
    else
        ip6tables $@
    fi

}
do_iptables() {
    if [ "$DEBUG" == "1" ]; then
        echo "iptables $@"
    else
        iptables $@
    fi
}
do_ipset() {
    if [ "$DEBUG" == "1" ]; then
        echo "ipset $@"
    else
        ipset $@
    fi
}
do_ip() {
    if [ "$DEBUG" == "1" ]; then
        echo "ip $@"
    else
        ip $@
    fi
}
do_ss_redir() {
    if [ "$DEBUG" == "1" ]; then
        echo "ss-redir $@"
    else
        ss-redir $@
    fi
}
clear_rules() {
    echo "Clearing rules"
    do_iptables -t nat -D OUTPUT -p tcp -j SHADOWSOCKS
    do_iptables -t nat -F SHADOWSOCKS
    do_iptables -t nat -X SHADOWSOCKS
    do_ipset destroy shadowsocks

    if [[ "$UDP" == "true" ]]; then
        do_iptables -t mangle -D PREROUTING -p udp -j SHADOWSOCKS
        do_iptables -t mangle -D OUTPUT -p udp -j SHADOWSOCKS_MARK
        do_iptables -t mangle -F SHADOWSOCKS
        do_iptables -t mangle -X SHADOWSOCKS
	do_iptables -t mangle -F SHADOWSOCKS_MARK
	do_iptables -t mangle -X SHADOWSOCKS_MARK
        do_ip rule del fwmark 1 lookup 100
        do_ip route del local default dev lo table 100
    fi

    if [[ "$IPV6" == "true" ]]; then
        do_iptables -D INPUT -p tcp --dport $LOCAL_PORT -j DROP
	    do_iptables -D INPUT -p tcp --dport $LOCAL_PORT -i lo -j ACCEPT
	    do_ip6tables -D INPUT -p tcp --dport $LOCAL_PORT -j DROP
	    do_ip6tables -D INPUT -p tcp --dport $LOCAL_PORT -i lo -j ACCEPT
	    do_ip6tables -t nat -D OUTPUT -p tcp -o lo -j RETURN
        do_ip6tables -t nat -D OUTPUT -p tcp -j REDIRECT --to-port $LOCAL_PORT
    fi

}
find_script_path() {
    SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
}

find_script_path

# MUST be run as root
if [ `id -u` != "0" ]; then
    echoerr "This script MUST BE run as ROOT"
    exit 1
fi

CONFIG_PATH="$1"

if [ "$CONFIG_PATH" == "" ]; then
    echoerr "Usage: shadowsocks-auto-redir <path to config.json>"
    exit 1
elif [ "$CONFIG_PATH" == "clear" ]; then
    clear_rules
    exit 0
elif [ ! -f "$CONFIG_PATH" ]; then
    echoerr "$CONFIG_PATH does not exist"
    exit 1
fi

do_iptables -t nat -N SHADOWSOCKS

# Bypass users
BYPASS_USERS=`jq -r ".ss_redir_options.bypass_users" $CONFIG_PATH`
if [[ "$BYPASS_USERS" != "null" ]]; then
    BYPASS_USERS=`jq -r ".ss_redir_options.bypass_users[]" $CONFIG_PATH`
    for user in $BYPASS_USERS; do
        do_iptables -t nat -A SHADOWSOCKS -m owner --uid-owner $user -j RETURN
        #do_ip6tables -t nat -A OUTPUT -m owner --uid-owner $user -j RETURN
    done
fi

# Bypass ips
SERVER=`jq -r ".server" $CONFIG_PATH`

if [[ $SERVER =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    if [[ $SERVER =~ "127."* ]]; then
        echo "Skipping local address $SERVER"
    else
        echo "Adding server IP $SERVER to bypass list"
        do_iptables -t nat -A SHADOWSOCKS -d $SERVER -j RETURN
    fi
else
    echo "Resolving server domain ${SERVER}"
    SERVER_IPS=$(drill A "$SERVER" | grep "^${SERVER}\.[[:space:]][0-9]\+[[:space:]]IN[[:space:]]A" | cut -f5)
    for ip in $SERVER_IPS ; do
        echo "Adding server IP $ip to bypass list"
        do_iptables -t nat -A SHADOWSOCKS -d "$ip" -j RETURN
    done
fi

BYPASS_IPS=`jq -r ".ss_redir_options.bypass_ips" $CONFIG_PATH`

if [[ "$BYPASS_IPS" != "null" ]]; then
    # Should only iterate when the item is not null
    BYPASS_IPS=`jq -r ".ss_redir_options.bypass_ips[]" $CONFIG_PATH`
    for ip in $BYPASS_IPS; do
        do_iptables -t nat -A SHADOWSOCKS -d $ip -j RETURN
    done
fi

# UDP
UDP=`jq -r ".ss_redir_options.udp" $CONFIG_PATH`

# Allow connection to preserved networks
do_iptables -t nat -A SHADOWSOCKS -d 0.0.0.0/8 -j RETURN
do_iptables -t nat -A SHADOWSOCKS -d 10.0.0.0/8 -j RETURN
do_iptables -t nat -A SHADOWSOCKS -d 127.0.0.0/8 -j RETURN
do_iptables -t nat -A SHADOWSOCKS -d 169.254.0.0/16 -j RETURN
do_iptables -t nat -A SHADOWSOCKS -d 172.16.0.0/12 -j RETURN
do_iptables -t nat -A SHADOWSOCKS -d 192.168.0.0/16 -j RETURN
do_iptables -t nat -A SHADOWSOCKS -d 224.0.0.0/4 -j RETURN
do_iptables -t nat -A SHADOWSOCKS -d 240.0.0.0/4 -j RETURN

# Load bypass route set
do_ipset -N shadowsocks hash:net maxelem 65536

BYPASS_PRESET=`jq -r ".ss_redir_options.bypass_preset" $CONFIG_PATH`

if [[ "$BYPASS_PRESET" == "chnroute" ]]; then
    for ip in `cat $SCRIPT_PATH/routes/chnroute.txt`; do
        do_ipset add shadowsocks $ip
    done
fi

do_iptables -t nat -A SHADOWSOCKS -m set --match-set shadowsocks dst -j RETURN

# Redirect to ss-redir port
LOCAL_PORT=`jq -r ".local_port" $CONFIG_PATH`

do_iptables -t nat -A SHADOWSOCKS -p tcp -j REDIRECT --to-port $LOCAL_PORT
do_iptables -t nat -A OUTPUT -p tcp -j SHADOWSOCKS
if [[ "$UDP" == "true" ]]; then
    do_ip rule add fwmark 1 lookup 100
    do_ip route add local default dev lo table 100
    do_iptables -t mangle -N SHADOWSOCKS
    do_iptables -t mangle -A SHADOWSOCKS -p udp -m mark --mark 1/1 -j TPROXY --on-port $LOCAL_PORT --tproxy-mark 1/1
    do_iptables -t mangle -A PREROUTING -p udp -j SHADOWSOCKS
    # Force reroute check for locally generated packets to go to te PREROUTING chain
    do_iptables -t mangle -N SHADOWSOCKS_MARK
    do_iptables -t mangle -A SHADOWSOCKS_MARK -o lo -j RETURN
    do_iptables -t mangle -A SHADOWSOCKS_MARK -d $SERVER -j RETURN
    do_iptables -t mangle -A SHADOWSOCKS_MARK -d 0.0.0.0/8 -j RETURN
    do_iptables -t mangle -A SHADOWSOCKS_MARK -d 10.0.0.0/8 -j RETURN
    do_iptables -t mangle -A SHADOWSOCKS_MARK -d 127.0.0.0/8 -j RETURN
    do_iptables -t mangle -A SHADOWSOCKS_MARK -d 169.254.0.0/16 -j RETURN
    do_iptables -t mangle -A SHADOWSOCKS_MARK -d 172.16.0.0/12 -j RETURN
    do_iptables -t mangle -A SHADOWSOCKS_MARK -d 192.168.0.0/16 -j RETURN
    do_iptables -t mangle -A SHADOWSOCKS_MARK -d 224.0.0.0/4 -j RETURN
    do_iptables -t mangle -A SHADOWSOCKS_MARK -d 240.0.0.0/4 -j RETURN
    do_iptables -t mangle -A SHADOWSOCKS_MARK -m set --match-set shadowsocks dst -j RETURN
    do_iptables -t mangle -A SHADOWSOCKS_MARK -p udp ! -o lo -j MARK --set-mark 1
    do_iptables -t mangle -A OUTPUT -p udp -j SHADOWSOCKS_MARK
fi

# IPv6 redirect to IPv4 Shadowsocks
# Please set local_address to ::
IPV6=`jq -r ".ss_redir_options.ipv6_to_ipv4" $CONFIG_PATH`

if [[ "$IPV6" == "true" ]]; then
    do_iptables -I INPUT -p tcp --dport $LOCAL_PORT -j DROP
	do_iptables -I INPUT -p tcp --dport $LOCAL_PORT -i lo -j ACCEPT
	do_ip6tables -I INPUT -p tcp --dport $LOCAL_PORT -j DROP
	do_ip6tables -I INPUT -p tcp --dport $LOCAL_PORT -i lo -j ACCEPT
	do_ip6tables -t nat -I OUTPUT -p tcp -o lo -j RETURN
    do_ip6tables -t nat -A OUTPUT -p tcp -j REDIRECT --to-port $LOCAL_PORT
    # TODO: Implement UDP forwarding for IPv6
fi

# Build ss-redir params
SS_PARAMS="-c $CONFIG_PATH"

if [[ `jq -r ".ss_redir_options.ota" $CONFIG_PATH` == "true" ]]; then
    SS_PARAMS="-A $SS_PARAMS"
fi

if [[ "$UDP" == "true" ]]; then
    SS_PARAMS="-u $SS_PARAMS"
fi

do_ss_redir $SS_PARAMS

# ss-redir has exited.
clear_rules
